// FUNCTIONS: write once, use multiple times.
// FUNCTIONS are reusable pieces of code.

// FUNCTION DEFINITION
function sum(){
    console.log(10 + 10);
}

// FUNCTIONS ARE NEVER EXECUTED ON THEIR OWN, THEY HAVE TO BE CALLED

// FUNCTION CALL
sum();


// FUNCTIONS WITH NO ARGUMENTS

// FUNCTIONS WITH ARGUMENTS

// FUNCTIONS HAVING DEFAULT ARGUMENT VALUES

// FUNCTION HAVING RETURN VALUES